### ISSUE TITLE
Running against tutorial(s) fails when app uses persistence

### ISSUE THREAD

**Issue by OnlyMeMate** [alexa/alexa-cookbook#240]
I run the Amazon Alexa video tutorial "Setup Local Debugging for an Alexa" Skill https://www.youtube.com/watch?v=RLQ8Oaj6Ccw, and debugging is successful on VSCode against "hello World" app, as in the video. However, running against any demo with persistence eg Cake Walk or High Low, the app fails as shown below:

  User  >  start high low game
  Alexa >  There was a problem with the requested skill's response

Is there some sort of permissions I need to set up to allow access to persistence locally? It's not specified in the tutorials documentation anywhere I can see.

[Note, running from the developer console with the endpoint (re)set to AWS Lambda works.]

debug window gives:
"~~~~ Error handled: Could not read item (amzn1.ask.account.AFV5QAE7QCLJQGHTK5EYAWRYARFW3HCGSAGBWXVBSSIGDUT4OR7YJ23CIPY7PD6LTEREB5URCGCSOPK6J4UDBSQUE6QMYFUQQ44T5KJ62BI3UZYNE4T6CZESOP4GYHOJ3JENFM44HKSZY4MC6T564AACOLP7HEIKGXDMN5WJQ7ZIK5GSC66LVRSFOH5HQ2JXHMG3D3HHMKK42SQ) from bucket (undefined): Missing required key 'Bucket' in params"

**Comment by OnlyMeMate** [comment]
~~~~ Error handled: Could not read item (amzn1.ask.account.AFV5QAE7QCLJQGHTK5EYAWRYARFW3HCGSAGBWXVBSSIGDUT4OR7YJ23CIPY7PD6LTEREB5URCGCSOPK6J4UDBSQUE6QMYFUQQ44T5KJ62BI3UZYNE4T6CZESOP4GYHOJ3JENFM44HKSZY4MC6T564AACOLP7HEIKGXDMN5WJQ7ZIK5GSC66LVRSFOH5HQ2JXHMG3D3HHMKK42SQ) from bucket (undefined): Missing required key 'Bucket' in params

**Comment by OnlyMeMate** [comment]
~~~~ Error handled: Could not read item (amzn1.ask.account.AFV5QAE7QCLJQGHTK5EYAWRYARFW3HCGSAGBWXVBSSIGDUT4OR7YJ23CIPY7PD6LTEREB5URCGCSOPK6J4UDBSQUE6QMYFUQQ44T5KJ62BI3UZYNE4T6CZESOP4GYHOJ3JENFM44HKSZY4MC6T564AACOLP7HEIKGXDMN5WJQ7ZIK5GSC66LVRSFOH5HQ2JXHMG3D3HHMKK42SQ) from bucket (undefined): Missing required key 'Bucket' in params

**Comment by OnlyMeMate** [comment]
"~~~~ Error handled: Could not read item (amzn1.ask.account.AFV5QAE7QCLJQGHTK5EYAWRYARFW3HCGSAGBWXVBSSIGDUT4OR7YJ23CIPY7PD6LTEREB5URCGCSOPK6J4UDBSQUE6QMYFUQQ44T5KJ62BI3UZYNE4T6CZESOP4GYHOJ3JENFM44HKSZY4MC6T564AACOLP7HEIKGXDMN5WJQ7ZIK5GSC66LVRSFOH5HQ2JXHMG3D3HHMKK42SQ) from bucket (undefined): Missing required key 'Bucket' in params"

**Comment by franklin-lobb** [comment]
Hi @OnlyMeMate  - I think there are two issues you'll have to contend with.

First, the bucket used by the persistence layer is typically set through a Lambda environment variable fetched by this code: `process.env.S3_PERSISTENCE_BUCKET`, since this variable is automatically set within the Hosted skill option.  When running locally, you won't have this environment variable set.  You can add the variable if you modify the VS Code configuration you are using to run the code.  This configuration is setup starting at 5:05 in the video, and needs `env` added after `args`: (`args` is included just to show placement - be sure to use the args values shown in the video.)
```
      "args": [ ... ],
      "env": {
        "S3_PERSISTENCE_BUCKET": "your_bucket_name"
      },
```
If you want to use the same bucket, you'll have to get the bucket name from your Lambda function's configuration, or if you'd rather use a different one for testing, then set it to another bucket in your AWS account.  (You could also manually set the bucket name without using an environment variable, provide a default value, branch the code, comment out lines of code depending on if you are running locally, etc.)

That brings us to the second issue - **permissions**.  You are correct that you'll need permissions to access the bucket. The AWS security context the local debugger will run under will normally be the default AWS profile configured on your machine, and that won't have access to the Hosted Skill's bucket.  So my recommendation is create a bucket in your own account that you can use for testing, which you'll have access to, but your testing won't be able to leverage any of the data stored in the hosted skill's bucket.  (If you're not using hosted but still using S3 persistence, then you should be good to go.)

If you really want to share the same bucket and use a hosted skill, you'll have to go down the route described here: https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#personal and then some.  I'd recommend just keeping planning to keep the local debugging persistence store separate. 

HTH

**Comment by OnlyMeMate** [comment]
Hi,
thanks for your reply, but I'm still having issues.
So, rather than use highlow which uses a dynamo db I cloned cake walk (hosted) - I call it "orange cake". It works fine in the developer console.
I run this in a batch file:
aws --profile this-alexa-user s3api create-bucket ^
  --bucket myverybestbucket ^
  --region us-east-1

the bucket exists in the console here: https://s3.console.aws.amazon.com/s3/buckets/myverybestbucket/?region=us-east-1

and so in launch.json:

            "args": [
                "--portNumber", "3001",
                "--skillEntryFile", "${workspaceRoot}/lambda/index.js",
                "--lambdaHandler", "handler"
            ],
            "env": {
                "S3_PERSISTENCE_BUCKET": "myverybestbucket"
              },

but still I get:

ask dialog --profile this-alexa-user --locale en-GB
User  >  open orange cake
Alexa >  The requested skill did not provide a valid response

As you can obviously tell I'm a novice with this and there's quite a learning curve, so apologies if I'm being dumb.

**Comment by franklin-lobb** [comment]
I'd guess that the default aws profile doesn't have access.  You're using a non-default profile by using this `--profile this-alexa-user`.  If you run this command from the command prompt `aws s3 ls`, you'll get a listing of all the buckets your default profile has access to.  If the bucket is listed, you might not have the right permissions, however you can change the profile used by default in your debug configuration by changing this section:
```
 "env": {
            "S3_PERSISTENCE_BUCKET": "myverybestbucket",
            "AWS_PROFILE": "this-alexa-user",      
          },
```

**Comment by OnlyMeMate** [comment]
Thanks.
It's a bit flakey, but got it working!

**Comment by franklin-lobb** [comment]
Sorry to hear it's a bit flakey, but glad to hear you got it working!

**Comment by YiddishNinja** [comment]
Hi, OnlyMeMate. Since you seem to be good, we're going to mark this issue closed. And Franklin, thanks for jumping in to help.
