### ISSUE TITLE
I am getting error in calling Lambda

### ISSUE THREAD

**Issue by amankohli** [alexa/alexa-cookbook#36]
I am getting the below error:
"The remote endpoint could not be called, or the response it returned was invalid."

I have followed the below tutorial:

"https://github.com/alexa/alexa-cookbook/tree/master/aws/Amazon-S3/read"

I have followed all the steps

**Comment by SleepyDeveloper** [comment]
Sounds like you have an error in your lambda function. From the `Service Simulator` in the amazon developer portal, copy the JSON from the `Service Request` and then go to your lambda.

Select Actions > Configure Test Event and paste the JSON into the box. Then click save and test. 

You'll get an error message, which should help you figure out what the problem is.

**Comment by amankohli** [comment]
Hi @SleepyDeveloper ,

Thank you for the reply,

I am getting a timeout error.

Below is the error:
"{
  "errorMessage": "2017-09-14T03:11:36.491Z 6958261b-98fa-11e7-b4a8-9117ffcca351 Task timed out after 3.00 seconds"
}"

I am using the alexa sdk with the code, I am zipping it and deploying it.

Please guide me where I am going wrong.
Regards,
Aman

**Comment by SleepyDeveloper** [comment]
If you go to your Lambda function and adjust your timeout to something longer than the default and try again does it complete before timing out?

**Comment by amankohli** [comment]
@SleepyDeveloper  Thank you the issue was resolved by increasing the time out to 10 seconds 👍
