### ISSUE TITLE
Magic Answers testing page - confused after role creation stage

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-cookbook#40]
Following along with the instructions - so far so good until...

https://github.com/alexa/alexa-cookbook/blob/master/aws/Amazon-DynamoDB/read/tests/webapp/README.md#add-permissions-to-users-of-your-identity-pool

Not seeing what I think I should be seeing - screenshots below. Where am I going wrong?

![screenclip 93](https://user-images.githubusercontent.com/1552808/30906316-66c1d59c-a36f-11e7-9143-f0c39b2b733f.png)

![screenclip 94](https://user-images.githubusercontent.com/1552808/30906398-aa34098a-a36f-11e7-91f6-4d4be4e21552.png)

**Comment by Liamdelee** [comment]
hello talkingnews,
to answer your question that is idd not the right place to be.
My first question is did you do the steps above this step?

**Create a new AWS Cognito Identity Pool

Login to the AWS Cognito console
Click "Manage Federated Identities"
Click "Create new identity pool" called magicpool
Check the box to "Enable access to unauthenticated providers"
Once your pool is created, click on the "Sample Code" menu item
Within your code, find the RED string called Identity Pool ID and remember this as your cognitoIdentityPoolID.**
Because if you did not do them you will idd not find **Cognito_magicpoolUnauth_Role** in your roles

if you can find this **Cognito_magicpoolUnauth_Role** in your roes just click on the name and you will be redirected to a new page. on this page just scroll down to the very bottom and on the bottom right you will find a button **add inline policy** just click this button. now you will again be redirected and just click the select button and from now just follow back your guide from step 6.

hope this helped

**Comment by talkingnews** [comment]
Thanks! Yup, pretty sure I did all that. At work right now, but might try and do either screenshots, or probably better a small screencam grab.

**Comment by Liamdelee** [comment]
just see where you can get with what i wrote down because if you see that screen i think it says that there is no roll and you need to create one or that you pushed the create roll button.

keep me updated of what is going on after work.

**Comment by SleepyDeveloper** [comment]
Have you been able to figure this out? Is it still an issue?

**Comment by franklin-lobb** [comment]
closing due to age
