### ISSUE TITLE
this.emit('PlanMyTrip') ends session if included in LaunchRequest handler

### ISSUE THREAD

**Issue by zebralight** [alexa/alexa-cookbook#71]
hello,

I was hoping to have the PlanMyTrip intent be triggered immediately upon launch and I tried to get that to happen by modifying the LaunchRequest handler as follows:

```
    'LaunchRequest': function () {
      this.response.speak(welcomeOutput).listen(welcomeReprompt);
      this.emit('PlanMyTrip');
    },
```
Unfortunately, doing so immediately ends my session.  I had tried even to move the body of the 'PlanMyTrip' handler into the 'LaunchRequest' handler to see if I'd get the expected behavior to no avail.  Any help would be much appreciated.

**Comment by Liamdelee** [comment]
Not sure why you would want that? because i think for certification you need to be able just opening the skill and get some help (Launchrequest). However it should work out if you just remove the  
`this.response.speak(welcomeOutput).listen(welcomeReprompt);`
At least that is what i am using (but not in LaunchRequest) so not sure if it will work out there.
Else just write an this.emit(':ask', "welcome, launch my skill as followed", "hello launch my skill as followed") and then in your VUI just make every answer route to your PlanMyTrip Intent. this is what i am doing and when i am in this Intent i just use an emit to go to the right Intent (i am using Dialog and using it to jump out of the dialog thingy).

**Comment by zebralight** [comment]
I'm working off of this file as my starting off point: https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/sample-nodejs-plan-my-trip/src/index.js .
My high-level view version of this is that the code as written has the user launch with 'plan my trip' and then call the intent handler by saying again 'plan my trip', and I want to remove the necessity for calling the intent handler on its first launch while being able to plan another trip by way of the user being prompted for a yes or no response with something like "would you like to plan another trip?".

my code above was my way of coaxing this desired behavior out of the code, to no success.  I feel like this particular refactor is trivial and doesn't require the introduction of states.  Unfortunately, I haven't been able to find any documentation nor sample code reflecting this behavior.

**Comment by SleepyDeveloper** [comment]
I've noticed a few things about your code. 

Firstly, in your LaunchRequest you're building the response but you're not emitting **:responseReady** so there's no way that your skill will speak the welcome prompt. 

Then when you emit **PlanMyTrip** it delegates to dialog collection `var filledSlots = delegateSlotCollection.call(this);`, your skill hasn't entered dialog management yet so the dialogState is undefined and you haven't been provided any slots. When I modified my code to match yours I got the following error.

    Unexpected exception 'TypeError: Cannot read property 'slots' of undefined':
    TypeError: Cannot read property 'slots' of undefined

I have a question for you. 

Why do want to force the user to say plan my trip twice? I know that would annoy the heck out of me to the point where I wouldn't want to use the skill. Your invocation name shouldn't be the same as your utterance, "Alexa, ask plan my trip to plan my trip" is unnatural. You should probably call it something like, trip planner. As you can see "Alexa, open trip planner" or "Alexa, ask trip planner to plan my trip" sound way more natural and are easier to say. Note if the user invokes the skill with an utterance (the latter of the two previous invocation phrases) the skill will immediately enter dialog management by running the PlanMyTripIntent instead of starting at the LaunchRequest.

I would also stay away from Yes/No questions as much as possible. It's a best practice to provide definitive choices.

Let's say the user books a trip from Seattle to Los Angeles from January 3rd to 14th and your skill has two intents PlanMyTripIntent and TripSummaryIntent. 

After planning a trip I would provide the following prompt, "Your trip to Los Angeles on January 3 has been booked. You're due to return to Seattle on January 14. Have fun! What would like me to do for you?"

Then in the reprompt I would have the skill say, "Which would you like me to do? Plan a trip or tell me about my trips" 

In that case you don't need to write any complicated logic to reinvoke the PlanMyTrip intent upon completion. You simply ask the user what they want to do and they'll tell you. If they're silent for 8 seconds the skill provides a definitive choice which makes the overall experience better.

**Comment by zebralight** [comment]
Hi Justin,

I may have poorly worded it.  The base code that the tutorial comes with has the user say plan my trip twice, and my goal is exactly to get rid of this as you said behavior that would "annoy the heck out of me."  Thanks for the advice with regards to refactoring the skill logic to avoid the yes/no built-in intents.  I was hoping that the invocation utterance "plan my trip" would have the effect of issuing the welcome message which would be executed in the launchrequest intent handler, then hand it off instantly to the PlanMyTrip intent handler for the first go, upon which I would implement the 'which would you like me to do?' part for reinvoking the PlanMyTrip intent handler.

**Comment by franklin-lobb** [comment]
@zebralight The current version of the sample prompts with a question as part of the LaunchRequest.  The answer to the question posed is a sample utterance for the PlanMyTrip Intent, so the user can get into the managed dialog connected with that Intent without having to repeat 'plan my trip'.

If the request passed to the skill is the LaunchRequest, you can trigger the same actions as another intent, but the skill's context isn't switched to the Intent configured for dialog management, which would be required for the delegate directive to be used.

**Comment by franklin-lobb** [comment]
closing due to age
