### ISSUE TITLE
What does Lab 8 mean in the instructions?

### ISSUE THREAD

**Issue by designserve** [alexa/alexa-cookbook#72]
Hi, I'm new to Github so forgive me if this is obvious. In the instructions it says:

**Instructions for deploying this sample skill
Complete Lab 8 within labs/HelloWorld to configure your AWS environment for persistent database storage.**

Following the link, I can't see anything called Lab 8 and I'm not able to understand which step to take to enable the database referred to in 'Last Use' (which directs me to this page to enable the database).

Side comment: I've followed a few tutorials now and there often seems to be an incorrect link with an error page when we get to the point of needing the code.

Thanks,
designserve

**Comment by SleepyDeveloper** [comment]
@designserve Sorry for the confusion. I will update the instructions to point directly to the page because it's pretty confusing since the lab numbers aren't included on the nav.

Here's the link to [lab 8](https://github.com/alexa/alexa-cookbook/blob/master/labs/HelloWorld/instructions/5-customization.md#lab-8---session-in-dynamodb)

We are constantly update the content in our tutorials. Could you provide a list of which ones have the wrong links and I get have them addressed.

**Comment by SleepyDeveloper** [comment]
@designserve I've updated the tutorial with the link lab 8 so it should take your right to it.

I'm going to close this issue. Cloud you create a new one with a list of links with broken code links?
