### ISSUE TITLE
Delegate Dialog Directive - "Provided Code" Links broken

### ISSUE THREAD

**Issue by thomfoolery** [alexa/alexa-cookbook#8]
Urls are broken on line 39 of _alexa-cookbook/handling-responses/dialog-directive-delegate/step-by-step/2-lambda-function.md_

**Comment by invictus2010** [comment]
Correct link is here: (https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/sample-nodejs-plan-my-trip/src/index.js))

**Comment by jezmck** [comment]
https://github.com/alexa/alexa-cookbook/pull/17

**Comment by SleepyDeveloper** [comment]
@jezmck  I made a change to this file yesterday because there was a similar issue reported and thus I missed your PR. I noticed that you have a link to the zip file as well as to the source which you can copy and paste. I think having both would be great for the user. Could I trouble you pull master  into your branch and resolve conflicts so I can merge your PR with a link to the zip file?

**Comment by jezmck** [comment]
I've *maybe* done that right, sorry if it's not!

**Comment by franklin-lobb** [comment]
closing due to age
